#!/bin/csh -fv

# copies log stuff over

# copy standard files over, bar a few special cases. This one deletes files at the destination
rsync -avu --delete --exclude="index*.html" --exclude="help*.html" --exclude="*.fits" --include="*/" --include="20*[0-9]" \
--include "*.html" --include "*.png" --exclude "*" logs $WEB_PATH/ultracam/.

# copy some links over. Can't do this for all because of extensive use of directory symlinks 
# which we want to leave untouched
rsync -avuL --exclude "*/*/" --include "*/" --include "*.css" --include "index*.html" \
--include="help*.html" --exclude "*" logs $WEB_PATH/ultracam/.

# copy fits to the Python directory
rsync -avu --include="*.fits" --exclude "*" logs/ $WEB_PATH/python/.

# copy some related Python scripts to the Python directory
rsync -avu --include="ucomment.py" --include="ulogs.py" --exclude "*" $HOME/code/C++/ultracam/logs/ $WEB_PATH/python/.

# copy some related php files scripts to the ultracam
rsync -avu --include="ucomment.php" --include="ulogs.php" --exclude "*" $HOME/code/C++/ultracam/logs/ $WEB_PATH/ultracam/logs/.

# make the permissions right

cd $WEB_PATH/ultracam
find logs -type d -exec \chmod 755 \{} \; 
find logs -type f -exec \chmod 644 \{} \;
find logs -name "*.py" -exec \chmod 755 \{} \;
