#!/bin/csh -fv

# copies log stuff over

# copy standard files over, bar a few special cases
rsync -avu --delete --exclude="index*.html" --exclude="help*.html" --exclude="*.fits" --include="*/" --include="20*[0-9]" \
--include "*.html" --include "*.png" --exclude "*" logs $WEB_PATH/ultracam/.

# copy some links over. Can't do this for all because of extensive use of directory symlinks which we
# want to leave alone
rsync -avuL --exclude "*/*/" --include "*/" --include "*.css" --include "*.php" --include "index*.html" \
--include="help*.html" --exclude "*" logs $WEB_PATH/ultracam/.

# copy fits
rsync -avu --include="*.fits" --exclude "*" logs/ $WEB_PATH/python/.

# make the permissions right

cd $WEB_PATH/ultracam
find logs -type d -exec \chmod 755 \{} \; 
find logs -type f -exec \chmod 644 \{} \;
find logs -name "*.py" -exec \chmod 755 \{} \;
