#!/bin/csh -fv

# copies log stuff over

# copy standard files over, bar a few special cases. This one deletes files at
# the destination
rsync -avu --delete --exclude="*.fits" --exclude="old_data/" --include="*/" \
--include="2*[0-9]" --include "*.html" --include "*.js" --include "*.png" \
--include "*.css" --include "*.json" --exclude "*" logs $WEB_PATH/ultraspec/.

# make the permissions right

cd $WEB_PATH/ultraspec
find logs -type d -exec \chmod 755 \{} \;
find logs -type f -exec \chmod 644 \{} \;
find logs -name "*.py" -exec \chmod 755 \{} \;
