#!/usr/bin/csh -v
#
# Copies files needed for online logs for ultraspec, ultracam
# This includes the night logs and some extras. They are
# copied into a single directory at the server end. The script
# should be invoked from the respective logs directory (checked)


if( $cwd != "/storage/astro1/phsaap/ultracam/logs" && \
    $cwd != "/storage/astro1/phsaap/ultraspec/logs" ) then
  echo "Must run from ultraspec or ultracam directories"
  exit(1))
endif

set dname  = `dirname $cwd`
set camera = `basename $dname`

set target = "/storage/astro2/www/phsaap/"$camera"/logs/."

rsync -avu --delete --exclude "old_data/" --include "*/" --include "20*.html" \
--include "ultra.json" --exclude "*" . $target

rsync -avuL --delete --include "./" --include "*.html" --include "*.js" \
--include "*.css" --include "index.php" --exclude "*" . $target
